// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("blazey.specifications")]
[assembly: AssemblyProductAttribute("blazey.specifications")]
[assembly: AssemblyDescriptionAttribute("mspec compatible xunit.net runner")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
